"""Walk-forward analysis driver for the ApexAlgo EA.

THE PROBLEM THIS SOLVES
    Run the MT5 optimiser over three years of EURUSD and it will hand you a
    parameter set with a beautiful equity curve. Trade it and it falls apart.
    The optimiser did not find an edge; it found the settings that best
    describe the noise in that particular slice of history.

THE FIX
    Split history into consecutive windows. Optimise on the first part of a
    window (in-sample), then test the winning parameters on the part that
    immediately follows and was never optimised on (out-of-sample). Slide
    forward and repeat. The out-of-sample results, stitched together, are the
    closest honest estimate of live behaviour you can get from history.

    The headline number is Walk-Forward Efficiency:

        WFE = out-of-sample return / in-sample return   (annualised)

    A robust system keeps a decent chunk of its in-sample performance. A
    curve-fitted one keeps almost none.

USAGE
    # 1. See the schedule and write the tester config files (any platform)
    python walkforward.py plan --start 2023-01-01 --end 2026-06-30 \
        --is-months 6 --oos-months 2 --symbol EURUSD

    # 2. Run them through the terminal (Windows, terminal must be closed)
    python walkforward.py run --terminal "C:\\Program Files\\MetaTrader 5\\terminal64.exe"

    # 3. Score the results
    python walkforward.py report

Only step 2 needs Windows and a MetaTrader installation. Steps 1 and 3 are
plain Python and are covered by the self-test (`python walkforward.py selftest`).
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, asdict
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

DEFAULT_WORKDIR = "walkforward"


# ----------------------------------------------------------------------
# Window schedule
# ----------------------------------------------------------------------
@dataclass
class Window:
    index: int
    is_start: date
    is_end: date
    oos_start: date
    oos_end: date

    def as_dict(self) -> Dict[str, str]:
        return {
            "index": self.index,
            "is_start": self.is_start.isoformat(),
            "is_end": self.is_end.isoformat(),
            "oos_start": self.oos_start.isoformat(),
            "oos_end": self.oos_end.isoformat(),
        }


def add_months(d: date, months: int) -> date:
    """Calendar-correct month arithmetic, clamping day-of-month overflow."""
    month_index = d.month - 1 + months
    year = d.year + month_index // 12
    month = month_index % 12 + 1
    # 31 January + 1 month must land on 28/29 February, not overflow into March
    for day in range(d.day, 0, -1):
        try:
            return date(year, month, day)
        except ValueError:
            continue
    raise ValueError("unreachable")


def build_windows(start: date, end: date, is_months: int, oos_months: int,
                  anchored: bool = False) -> List[Window]:
    """Rolling (default) or anchored walk-forward windows.

    Rolling  : the in-sample window slides, so old regimes drop out.
    Anchored : the in-sample window only grows from a fixed origin.

    Rolling is the stricter test and the default. Anchored tends to flatter
    a strategy because early, favourable history never leaves the sample.
    """
    if is_months < 1 or oos_months < 1:
        raise ValueError("in-sample and out-of-sample lengths must be at least 1 month")
    if end <= start:
        raise ValueError("end date must be after start date")

    windows: List[Window] = []
    cursor = start
    index = 1

    while True:
        is_start = start if anchored else cursor
        is_end = add_months(cursor, is_months)
        oos_start = is_end
        oos_end = add_months(oos_start, oos_months)

        if oos_end > end:
            break

        windows.append(Window(index, is_start, is_end, oos_start, oos_end))
        cursor = add_months(cursor, oos_months)
        index += 1

        if index > 500:  # guard against a pathological schedule
            break

    if not windows:
        raise ValueError(
            f"the range {start} to {end} is too short for "
            f"{is_months}-month in-sample + {oos_months}-month out-of-sample windows"
        )
    return windows


# ----------------------------------------------------------------------
# Tester .ini generation
# ----------------------------------------------------------------------
INI_TEMPLATE = """; ApexAlgo walk-forward - generated by walkforward.py, do not edit by hand
[Tester]
Expert={expert}
Symbol={symbol}
Period={period}
Model={model}
ExecutionMode=0
Optimization={optimization}
OptimizationCriterion={criterion}
FromDate={from_date}
ToDate={to_date}
ForwardMode=0
Deposit={deposit}
Currency={currency}
Leverage={leverage}
ProfitInPips=0
Report={report}
ReplaceReport=1
ShutdownTerminal=1
Visual=0

[TesterInputs]
{inputs}
"""

# Parameters worth optimising, with sane search ranges.
#
# Deliberately short. Every extra parameter multiplies the search space and
# the chance of fitting noise; a walk-forward run over six free parameters is
# already generous. Risk settings are NOT optimised - they are a policy
# decision about survival, not a variable to be maximised.
DEFAULT_OPTIMIZE = {
    # name: (start, step, stop)
    "InpMinScore": (0.35, 0.05, 0.60),
    "InpAtrStopTrend": (1.5, 0.5, 3.0),
    "InpRRTrend": (1.5, 0.5, 3.0),
    "InpAdxTrendMin": (20.0, 2.0, 28.0),
    "InpDonchianPeriod": (15, 5, 30),
    "InpTrailAtrMult": (1.5, 0.5, 3.0),
}

# Held fixed across every run so the comparison is apples to apples.
DEFAULT_FIXED = {
    "InpRiskPercent": 0.5,
    "InpMaxPositionsTotal": 4,
    "InpDailyLossLimitPct": 3.0,
    "InpMaxDrawdownPct": 10.0,
    "InpRemoteEnabled": "false",
    "InpLogToFile": "false",
    "InpUseNewsFilter": "false",  # the calendar is unavailable in the tester
    "InpShowPanel": "false",
}


def format_input(name: str, value: Any, optimize: Optional[Tuple] = None) -> str:
    """MT5 [TesterInputs] line: value||start||step||stop||optimize_flag"""
    if optimize is None:
        return f"{name}={value}"
    start, step, stop = optimize
    return f"{name}={start}||{start}||{step}||{stop}||Y"


def write_ini(path: str, *, expert: str, symbol: str, period: str, model: int,
              optimization: int, criterion: int, from_date: date, to_date: date,
              deposit: int, currency: str, leverage: int, report: str,
              optimize_params: Dict[str, Tuple], fixed_params: Dict[str, Any],
              best_params: Optional[Dict[str, Any]] = None) -> None:
    lines: List[str] = []

    for name, value in fixed_params.items():
        lines.append(format_input(name, value))

    if best_params is not None:
        # Out-of-sample run: pin the winners, optimise nothing.
        for name, value in best_params.items():
            lines.append(format_input(name, value))
    else:
        for name, bounds in optimize_params.items():
            lines.append(format_input(name, bounds[0], bounds))

    content = INI_TEMPLATE.format(
        expert=expert, symbol=symbol, period=period, model=model,
        optimization=optimization, criterion=criterion,
        from_date=from_date.strftime("%Y.%m.%d"),
        to_date=to_date.strftime("%Y.%m.%d"),
        deposit=deposit, currency=currency, leverage=leverage,
        report=report, inputs="\n".join(lines),
    )
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


# ----------------------------------------------------------------------
# Report parsing
# ----------------------------------------------------------------------
# MT5 writes its single-run report as HTML with a two-column table. The labels
# are stable across builds; the numbers are locale-formatted, so they are
# normalised before parsing.
REPORT_FIELDS = {
    "net_profit": ["Total Net Profit", "Total net profit"],
    "gross_profit": ["Gross Profit", "Gross profit"],
    "gross_loss": ["Gross Loss", "Gross loss"],
    "profit_factor": ["Profit Factor", "Profit factor"],
    "expected_payoff": ["Expected Payoff", "Expected payoff"],
    "max_drawdown_pct": ["Equity Drawdown Maximal", "Balance Drawdown Maximal"],
    "trades": ["Total Trades", "Total trades"],
    "sharpe": ["Sharpe Ratio", "Sharpe ratio"],
    "recovery_factor": ["Recovery Factor", "Recovery factor"],
}


def _to_number(raw: str) -> Optional[float]:
    if raw is None:
        return None
    text = raw.strip()
    # "1 234.56 (12.34%)" -> take the leading number
    text = re.sub(r"\(.*?\)", "", text)
    text = text.replace("\xa0", "").replace(" ", "").replace("%", "")
    # thousands separators: 1,234.56 or 1.234,56
    if re.match(r"^-?\d{1,3}(,\d{3})+(\.\d+)?$", text):
        text = text.replace(",", "")
    elif re.match(r"^-?\d{1,3}(\.\d{3})+(,\d+)?$", text):
        text = text.replace(".", "").replace(",", ".")
    else:
        text = text.replace(",", ".")
    match = re.search(r"-?\d+(?:\.\d+)?", text)
    return float(match.group()) if match else None


def parse_html_report(path: str) -> Dict[str, Any]:
    """Pull the headline metrics out of an MT5 single-run HTML report."""
    with open(path, "r", encoding="utf-8", errors="ignore") as fh:
        html = fh.read()

    # Flatten the table into a list of cell texts, then read label/value pairs.
    cells = re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", html, re.S | re.I)
    cells = [re.sub(r"<[^>]+>", "", c).replace("&nbsp;", " ").strip() for c in cells]

    out: Dict[str, Any] = {"source": os.path.basename(path)}
    for key, labels in REPORT_FIELDS.items():
        value = None
        for i, cell in enumerate(cells):
            stripped = cell.rstrip(":").strip()
            if any(stripped.lower() == label.lower() for label in labels):
                for j in range(i + 1, min(i + 4, len(cells))):
                    value = _to_number(cells[j])
                    if value is not None:
                        break
                break
        out[key] = value

    # "Equity Drawdown Maximal" reports money then a percentage in brackets.
    for label in ("Equity Drawdown Maximal", "Balance Drawdown Maximal"):
        for i, cell in enumerate(cells):
            if cell.rstrip(":").strip().lower() == label.lower():
                for j in range(i + 1, min(i + 4, len(cells))):
                    pct = re.search(r"\(([\d.,\s]+)%\)", cells[j])
                    if pct:
                        out["max_drawdown_pct"] = _to_number(pct.group(1))
                        break
                break

    return out


# ----------------------------------------------------------------------
# Scoring
# ----------------------------------------------------------------------
def annualised_return(net_profit: float, deposit: float, days: int) -> Optional[float]:
    if deposit <= 0 or days <= 0:
        return None
    total_return = net_profit / deposit
    # simple scaling, not compounding: compounding a 2-month sample into an
    # annual figure produces numbers nobody should act on
    return total_return * (365.0 / days)


def score_walkforward(rows: List[Dict[str, Any]], deposit: float) -> Dict[str, Any]:
    """Aggregate per-window results into a verdict."""
    usable = [r for r in rows if r.get("oos_net_profit") is not None]
    if not usable:
        return {"windows": 0, "verdict": "no out-of-sample results to score"}

    efficiencies = []
    for row in usable:
        is_days = int(row.get("is_days") or 0)
        oos_days = int(row.get("oos_days") or 0)
        is_annual = annualised_return(float(row.get("is_net_profit") or 0.0), deposit, is_days)
        oos_annual = annualised_return(float(row["oos_net_profit"]), deposit, oos_days)
        row["is_annualised"] = is_annual
        row["oos_annualised"] = oos_annual
        # Efficiency is only meaningful when the in-sample run actually made
        # money. A negative in-sample result means the optimisation failed,
        # not that the strategy is robust.
        if is_annual and is_annual > 0 and oos_annual is not None:
            row["efficiency"] = oos_annual / is_annual
            efficiencies.append(row["efficiency"])
        else:
            row["efficiency"] = None

    oos_profits = [float(r["oos_net_profit"]) for r in usable]
    profitable = [p for p in oos_profits if p > 0]
    total_oos = sum(oos_profits)

    drawdowns = [float(r["oos_max_drawdown_pct"]) for r in usable
                 if r.get("oos_max_drawdown_pct") is not None]
    trades = sum(int(r.get("oos_trades") or 0) for r in usable)

    mean_efficiency = sum(efficiencies) / len(efficiencies) if efficiencies else None
    consistency = 100.0 * len(profitable) / len(usable)

    # The verdict is intentionally conservative. These thresholds come from
    # standard walk-forward practice, not from this strategy's own results.
    if total_oos <= 0:
        verdict = "REJECT - out-of-sample is net negative"
    elif trades < 100:
        verdict = "INCONCLUSIVE - fewer than 100 out-of-sample trades"
    elif mean_efficiency is not None and mean_efficiency < 0.35:
        verdict = "REJECT - out-of-sample keeps under 35% of in-sample performance"
    elif consistency < 50.0:
        verdict = "REJECT - fewer than half the out-of-sample windows were profitable"
    elif mean_efficiency is not None and mean_efficiency > 1.5:
        verdict = "SUSPICIOUS - out-of-sample beats in-sample; check for look-ahead bias"
    elif mean_efficiency is not None and mean_efficiency >= 0.5 and consistency >= 60.0:
        verdict = "PASS - candidate for demo forward testing"
    else:
        verdict = "MARGINAL - retest with different windows before risking capital"

    return {
        "windows": len(usable),
        "oos_net_profit": round(total_oos, 2),
        "oos_trades": trades,
        "profitable_windows": len(profitable),
        "consistency_pct": round(consistency, 1),
        "mean_efficiency": round(mean_efficiency, 3) if mean_efficiency is not None else None,
        "worst_oos_window": round(min(oos_profits), 2),
        "best_oos_window": round(max(oos_profits), 2),
        "worst_oos_drawdown_pct": round(max(drawdowns), 2) if drawdowns else None,
        "verdict": verdict,
    }


# ----------------------------------------------------------------------
# Commands
# ----------------------------------------------------------------------
def cmd_plan(args) -> int:
    start = datetime.strptime(args.start, "%Y-%m-%d").date()
    end = datetime.strptime(args.end, "%Y-%m-%d").date()
    windows = build_windows(start, end, args.is_months, args.oos_months, args.anchored)

    workdir = os.path.abspath(args.workdir)
    ini_dir = os.path.join(workdir, "ini")
    os.makedirs(ini_dir, exist_ok=True)

    fixed = dict(DEFAULT_FIXED)
    if args.fixed:
        fixed.update(json.loads(args.fixed))

    plan = {
        "symbol": args.symbol,
        "period": args.period,
        "expert": args.expert,
        "deposit": args.deposit,
        "currency": args.currency,
        "leverage": args.leverage,
        "model": args.model,
        "anchored": args.anchored,
        "windows": [w.as_dict() for w in windows],
    }

    print(f"{len(windows)} walk-forward window(s), {args.symbol} {args.period}")
    print(f"{'#':>3}  {'in-sample':<26} {'out-of-sample':<26}")
    print("-" * 60)
    for w in windows:
        print(f"{w.index:>3}  {w.is_start} -> {w.is_end}   {w.oos_start} -> {w.oos_end}")

        write_ini(
            os.path.join(ini_dir, f"w{w.index:02d}_is.ini"),
            expert=args.expert, symbol=args.symbol, period=args.period, model=args.model,
            optimization=2, criterion=args.criterion,
            from_date=w.is_start, to_date=w.is_end,
            deposit=args.deposit, currency=args.currency, leverage=args.leverage,
            report=os.path.join(workdir, "reports", f"w{w.index:02d}_is"),
            optimize_params=DEFAULT_OPTIMIZE, fixed_params=fixed,
        )
        write_ini(
            os.path.join(ini_dir, f"w{w.index:02d}_oos.ini"),
            expert=args.expert, symbol=args.symbol, period=args.period, model=args.model,
            optimization=0, criterion=args.criterion,
            from_date=w.oos_start, to_date=w.oos_end,
            deposit=args.deposit, currency=args.currency, leverage=args.leverage,
            report=os.path.join(workdir, "reports", f"w{w.index:02d}_oos"),
            optimize_params=DEFAULT_OPTIMIZE, fixed_params=fixed,
            best_params={name: bounds[0] for name, bounds in DEFAULT_OPTIMIZE.items()},
        )

    with open(os.path.join(workdir, "plan.json"), "w", encoding="utf-8") as fh:
        json.dump(plan, fh, indent=2)

    print()
    print(f"config files : {ini_dir}")
    print(f"plan         : {os.path.join(workdir, 'plan.json')}")
    print()
    print("Next: run each in-sample .ini, read the winning parameters out of the")
    print("optimisation table, write them into the matching _oos.ini, then run that.")
    print("`walkforward.py run` automates the launching; MT5 cannot export the")
    print("optimisation winners automatically, so that one step stays manual.")
    return 0


def cmd_run(args) -> int:
    workdir = os.path.abspath(args.workdir)
    ini_dir = os.path.join(workdir, "ini")
    if not os.path.isdir(ini_dir):
        print(f"no config files in {ini_dir}. Run `walkforward.py plan` first.")
        return 1

    if not os.path.exists(args.terminal):
        print(f"terminal not found: {args.terminal}")
        return 1

    pattern = "_oos.ini" if args.stage == "oos" else "_is.ini"
    files = sorted(f for f in os.listdir(ini_dir) if f.endswith(pattern))
    if not files:
        print(f"no {args.stage} config files found")
        return 1

    print(f"running {len(files)} {args.stage} pass(es)")
    print("The terminal must be CLOSED before starting, and will open and close")
    print("itself once per window. This takes a while.\n")

    for name in files:
        ini_path = os.path.join(ini_dir, name)
        print(f"  -> {name}", flush=True)
        try:
            subprocess.run([args.terminal, f"/config:{ini_path}"],
                           check=False, timeout=args.timeout)
        except subprocess.TimeoutExpired:
            print(f"     timed out after {args.timeout}s, moving on")
    print("\ndone. Reports are in", os.path.join(workdir, "reports"))
    return 0


def cmd_report(args) -> int:
    workdir = os.path.abspath(args.workdir)
    reports_dir = os.path.join(workdir, "reports")
    plan_path = os.path.join(workdir, "plan.json")

    if not os.path.exists(plan_path):
        print(f"no plan.json in {workdir}. Run `walkforward.py plan` first.")
        return 1

    with open(plan_path, encoding="utf-8") as fh:
        plan = json.load(fh)

    rows: List[Dict[str, Any]] = []
    for window in plan["windows"]:
        index = window["index"]
        row: Dict[str, Any] = {
            "window": index,
            "is_start": window["is_start"], "is_end": window["is_end"],
            "oos_start": window["oos_start"], "oos_end": window["oos_end"],
        }
        row["is_days"] = (datetime.fromisoformat(window["is_end"])
                          - datetime.fromisoformat(window["is_start"])).days
        row["oos_days"] = (datetime.fromisoformat(window["oos_end"])
                           - datetime.fromisoformat(window["oos_start"])).days

        for stage in ("is", "oos"):
            for ext in (".html", ".htm"):
                path = os.path.join(reports_dir, f"w{index:02d}_{stage}{ext}")
                if os.path.exists(path):
                    parsed = parse_html_report(path)
                    for key, value in parsed.items():
                        if key != "source":
                            row[f"{stage}_{key}"] = value
                    break
        rows.append(row)

    summary = score_walkforward(rows, float(plan.get("deposit", 10000)))

    print(f"Walk-forward report - {plan['symbol']} {plan['period']}")
    print("=" * 74)
    print(f"{'#':>3} {'OOS window':<25} {'OOS net':>10} {'DD%':>7} {'trades':>7} {'eff':>7}")
    print("-" * 74)
    for row in rows:
        net = row.get("oos_net_profit")
        eff = row.get("efficiency")
        dd = row.get("oos_max_drawdown_pct")
        trades = row.get("oos_trades")

        net_text = f"{net:.2f}" if net is not None else "--"
        dd_text = f"{dd:.2f}" if dd is not None else "--"
        eff_text = f"{eff:.2f}" if eff is not None else "--"
        trades_text = str(trades) if trades is not None else "--"
        window_text = f"{row['oos_start']} -> {row['oos_end']}"

        print(f"{row['window']:>3} {window_text:<25} {net_text:>10} "
              f"{dd_text:>7} {trades_text:>7} {eff_text:>7}")

    print("=" * 74)
    for key, value in summary.items():
        print(f"{key:<24}: {value}")

    csv_path = os.path.join(workdir, "walkforward_results.csv")
    if rows:
        keys = sorted({k for row in rows for k in row})
        with open(csv_path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=keys)
            writer.writeheader()
            writer.writerows(rows)
        print(f"\nper-window results written to {csv_path}")

    with open(os.path.join(workdir, "walkforward_summary.json"), "w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=2)

    return 0


def cmd_selftest(args) -> int:
    """Covers everything that does not need MetaTrader."""
    failures: List[str] = []

    def check(name: str, condition: bool, extra: Any = "") -> None:
        print(("  PASS  " if condition else "  FAIL  ") + name
              + (f"  -> {extra}" if extra and not condition else ""))
        if not condition:
            failures.append(name)

    print("== month arithmetic ==")
    check("simple add", add_months(date(2024, 1, 15), 2) == date(2024, 3, 15))
    check("year rollover", add_months(date(2024, 11, 10), 3) == date(2025, 2, 10))
    check("jan 31 + 1 month clamps to feb 29 in a leap year",
          add_months(date(2024, 1, 31), 1) == date(2024, 2, 29),
          add_months(date(2024, 1, 31), 1))
    check("jan 31 + 1 month clamps to feb 28 otherwise",
          add_months(date(2023, 1, 31), 1) == date(2023, 2, 28),
          add_months(date(2023, 1, 31), 1))
    check("negative months", add_months(date(2024, 3, 15), -4) == date(2023, 11, 15))

    print("\n== window schedule ==")
    # 12 months of history, 6-month IS + 2-month OOS, sliding 2 months at a
    # time, yields 3 complete windows: the 4th would need data past the end.
    windows = build_windows(date(2024, 1, 1), date(2025, 1, 1), 6, 2)
    check("expected window count", len(windows) == 3, len(windows))
    check("last window ends exactly on the end date",
          windows[-1].oos_end == date(2025, 1, 1), windows[-1].oos_end)
    check("first window in-sample", (windows[0].is_start, windows[0].is_end)
          == (date(2024, 1, 1), date(2024, 7, 1)), windows[0])
    check("out-of-sample starts where in-sample ends",
          all(w.is_end == w.oos_start for w in windows))
    check("windows advance by the OOS length",
          windows[1].is_start == add_months(windows[0].is_start, 2), windows[1].is_start)
    check("no window runs past the end date", all(w.oos_end <= date(2025, 1, 1) for w in windows))

    anchored = build_windows(date(2024, 1, 1), date(2025, 1, 1), 6, 2, anchored=True)
    check("anchored windows share one origin",
          all(w.is_start == date(2024, 1, 1) for w in anchored))
    check("anchored in-sample grows", anchored[-1].is_end > anchored[0].is_end)

    for bad, label in [((date(2024, 1, 1), date(2024, 2, 1), 6, 2), "range too short"),
                       ((date(2024, 1, 1), date(2023, 1, 1), 6, 2), "end before start"),
                       ((date(2024, 1, 1), date(2025, 1, 1), 0, 2), "zero in-sample")]:
        try:
            build_windows(*bad)
            ok = False
        except ValueError:
            ok = True
        check(f"rejects {label}", ok)

    print("\n== number normalisation ==")
    cases = [("1 234.56", 1234.56), ("1,234.56", 1234.56), ("1.234,56", 1234.56),
             ("-567.89", -567.89), ("12.34%", 12.34), ("1 234.56 (12.34%)", 1234.56),
             ("2 998", 2998.0), ("0.00", 0.0)]
    for raw, expected in cases:
        got = _to_number(raw)
        check(f"parses {raw!r}", got is not None and abs(got - expected) < 1e-9, got)
    check("garbage yields None", _to_number("n/a") is None, _to_number("n/a"))

    print("\n== report parsing ==")
    sample_html = """<html><body><table>
      <tr><td>Total Net Profit:</td><td>1 234.56</td><td>Gross Profit:</td><td>5 000.00</td></tr>
      <tr><td>Gross Loss:</td><td>-3 765.44</td><td>Profit Factor:</td><td>1.33</td></tr>
      <tr><td>Expected Payoff:</td><td>12.35</td><td>Recovery Factor:</td><td>2.10</td></tr>
      <tr><td>Equity Drawdown Maximal:</td><td>588.00 (5.88%)</td></tr>
      <tr><td>Total Trades:</td><td>100</td><td>Sharpe Ratio:</td><td>0.42</td></tr>
    </table></body></html>"""
    tmp = os.path.join(args.workdir if args.workdir else ".", "_wf_selftest.html")
    os.makedirs(os.path.dirname(os.path.abspath(tmp)), exist_ok=True)
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(sample_html)
    parsed = parse_html_report(tmp)
    os.remove(tmp)
    check("net profit", parsed["net_profit"] == 1234.56, parsed["net_profit"])
    check("profit factor", parsed["profit_factor"] == 1.33, parsed["profit_factor"])
    check("trades", parsed["trades"] == 100, parsed["trades"])
    check("drawdown percent from brackets", parsed["max_drawdown_pct"] == 5.88,
          parsed["max_drawdown_pct"])
    check("sharpe", parsed["sharpe"] == 0.42, parsed["sharpe"])

    print("\n== scoring ==")
    robust = [{"is_net_profit": 1000, "oos_net_profit": 400, "is_days": 180,
               "oos_days": 60, "oos_trades": 40, "oos_max_drawdown_pct": 4.0}
              for _ in range(4)]
    verdict = score_walkforward([dict(r) for r in robust], 10000)
    check("robust set passes", verdict["verdict"].startswith("PASS"), verdict["verdict"])
    check("efficiency around 1.2", abs(verdict["mean_efficiency"] - 1.2) < 0.01,
          verdict["mean_efficiency"])
    check("consistency 100%", verdict["consistency_pct"] == 100.0)

    fitted = [{"is_net_profit": 3000, "oos_net_profit": -200, "is_days": 180,
               "oos_days": 60, "oos_trades": 40, "oos_max_drawdown_pct": 9.0}
              for _ in range(4)]
    verdict = score_walkforward([dict(r) for r in fitted], 10000)
    check("curve-fitted set is rejected", verdict["verdict"].startswith("REJECT"),
          verdict["verdict"])

    thin = [{"is_net_profit": 800, "oos_net_profit": 300, "is_days": 180,
             "oos_days": 60, "oos_trades": 4, "oos_max_drawdown_pct": 3.0}
            for _ in range(3)]
    verdict = score_walkforward([dict(r) for r in thin], 10000)
    check("too few trades is inconclusive", verdict["verdict"].startswith("INCONCLUSIVE"),
          verdict["verdict"])

    toogood = [{"is_net_profit": 200, "oos_net_profit": 900, "is_days": 180,
                "oos_days": 60, "oos_trades": 60, "oos_max_drawdown_pct": 2.0}
               for _ in range(4)]
    verdict = score_walkforward([dict(r) for r in toogood], 10000)
    check("implausible outperformance is flagged", verdict["verdict"].startswith("SUSPICIOUS"),
          verdict["verdict"])

    verdict = score_walkforward([], 10000)
    check("empty input handled", verdict["windows"] == 0, verdict)

    print("\n== ini generation ==")
    ini_path = os.path.join(args.workdir if args.workdir else ".", "_wf_selftest.ini")
    write_ini(ini_path, expert="ApexAlgo\\ApexAlgoEA", symbol="EURUSD", period="M15",
              model=1, optimization=2, criterion=6,
              from_date=date(2024, 1, 1), to_date=date(2024, 7, 1),
              deposit=10000, currency="USD", leverage=100, report="r",
              optimize_params=DEFAULT_OPTIMIZE, fixed_params=DEFAULT_FIXED)
    text = open(ini_path, encoding="utf-8").read()
    os.remove(ini_path)
    check("has [Tester] section", "[Tester]" in text)
    check("has [TesterInputs] section", "[TesterInputs]" in text)
    check("dates use MT5 dotted format", "FromDate=2024.01.01" in text, text[:200])
    check("optimised inputs carry the Y flag", "InpMinScore=0.35||0.35||0.05||0.6||Y" in text,
          [l for l in text.splitlines() if l.startswith("InpMinScore")])
    check("fixed inputs have no range", "InpRiskPercent=0.5" in text)
    check("news filter off in the tester", "InpUseNewsFilter=false" in text)

    print("\n" + "=" * 60)
    if failures:
        print(f"{len(failures)} CHECK(S) FAILED: {failures}")
        return 1
    print("ALL CHECKS PASSED")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Walk-forward analysis driver for the ApexAlgo EA",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--workdir", default=DEFAULT_WORKDIR)
    sub = parser.add_subparsers(dest="command", required=True)

    p_plan = sub.add_parser("plan", help="build the window schedule and tester configs")
    p_plan.add_argument("--start", required=True, help="YYYY-MM-DD")
    p_plan.add_argument("--end", required=True, help="YYYY-MM-DD")
    p_plan.add_argument("--is-months", type=int, default=6, dest="is_months")
    p_plan.add_argument("--oos-months", type=int, default=2, dest="oos_months")
    p_plan.add_argument("--anchored", action="store_true",
                        help="grow the in-sample window instead of sliding it")
    p_plan.add_argument("--symbol", default="EURUSD")
    p_plan.add_argument("--period", default="M15")
    p_plan.add_argument("--expert", default="ApexAlgo\\ApexAlgoEA")
    p_plan.add_argument("--deposit", type=int, default=10000)
    p_plan.add_argument("--currency", default="USD")
    p_plan.add_argument("--leverage", type=int, default=100)
    p_plan.add_argument("--model", type=int, default=1,
                        help="0 every tick, 1 1-minute OHLC, 2 open prices, 4 real ticks")
    p_plan.add_argument("--criterion", type=int, default=6,
                        help="MT5 optimisation criterion (6 = complex criterion)")
    p_plan.add_argument("--fixed", default="", help="JSON object of extra fixed inputs")
    p_plan.set_defaults(func=cmd_plan)

    p_run = sub.add_parser("run", help="launch the terminal for each config")
    p_run.add_argument("--terminal", required=True, help="path to terminal64.exe")
    p_run.add_argument("--stage", choices=["is", "oos"], default="is")
    p_run.add_argument("--timeout", type=int, default=7200, help="seconds per pass")
    p_run.set_defaults(func=cmd_run)

    p_report = sub.add_parser("report", help="score the finished runs")
    p_report.set_defaults(func=cmd_report)

    p_self = sub.add_parser("selftest", help="verify the tooling itself")
    p_self.set_defaults(func=cmd_selftest)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
