//+------------------------------------------------------------------+
//|                                                         Json.mqh |
//|   ApexAlgo - minimal JSON writer + tolerant reader for flat maps |
//|                                                                  |
//| MQL5 has no JSON support. A full parser is overkill here: the EA  |
//| only ever produces its own payloads and consumes a small, known   |
//| command schema from its own server. This keeps the surface tiny   |
//| and predictable instead of pulling in a large third-party parser. |
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| CJsonWriter - builds compact JSON objects/arrays                 |
//+------------------------------------------------------------------+
#ifndef APEX_JSON_MQH
#define APEX_JSON_MQH

class CJsonWriter
  {
private:
   string            m_buf;
   bool              m_first;

   string            Escape(const string s)
     {
      string r=s;
      StringReplace(r,"\\","\\\\");
      StringReplace(r,"\"","\\\"");
      StringReplace(r,"\n","\\n");
      StringReplace(r,"\r","\\r");
      StringReplace(r,"\t","\\t");
      return r;
     }

   void              Sep(void)
     {
      if(!m_first) m_buf+=",";
      m_first=false;
     }

public:
                     CJsonWriter(void) { Reset(); }

   void              Reset(void)
     {
      m_buf="{";
      m_first=true;
     }

   void              Str(const string key,const string val)
     {
      Sep();
      m_buf+=StringFormat("\"%s\":\"%s\"",Escape(key),Escape(val));
     }

   void              Num(const string key,const double val,const int digits=6)
     {
      Sep();
      // MQL5 prints nan/inf in a way JSON parsers reject - clamp them out
      double v=val;
      if(!MathIsValidNumber(v)) v=0.0;
      m_buf+=StringFormat("\"%s\":%s",Escape(key),DoubleToString(v,digits));
     }

   void              Int(const string key,const long val)
     {
      Sep();
      m_buf+=StringFormat("\"%s\":%I64d",Escape(key),val);
     }

   void              Bool(const string key,const bool val)
     {
      Sep();
      m_buf+=StringFormat("\"%s\":%s",Escape(key),(val?"true":"false"));
     }

   //--- embed an already-serialised object or array verbatim
   void              Raw(const string key,const string rawJson)
     {
      Sep();
      m_buf+=StringFormat("\"%s\":%s",Escape(key),rawJson);
     }

   string            Finish(void)
     {
      return m_buf+"}";
     }
  };

//+------------------------------------------------------------------+
//| Reader helpers                                                   |
//|                                                                  |
//| These scan for "key": and read the value that follows. They are   |
//| deliberately simple: the command schema is flat, generated by our |
//| own server, and every field is validated by the caller anyway.    |
//+------------------------------------------------------------------+

//--- locate the position just after "key": , or -1 ------------------
int JsonFindValuePos(const string json,const string key,const int from=0)
  {
   string needle="\""+key+"\"";
   int p=StringFind(json,needle,from);
   if(p<0) return -1;
   p+=StringLen(needle);
   // skip whitespace then the colon then whitespace
   int len=StringLen(json);
   while(p<len)
     {
      ushort c=StringGetCharacter(json,p);
      if(c==' '||c=='\t'||c=='\n'||c=='\r') { p++; continue; }
      break;
     }
   if(p>=len || StringGetCharacter(json,p)!=':') return -1;
   p++;
   while(p<len)
     {
      ushort c=StringGetCharacter(json,p);
      if(c==' '||c=='\t'||c=='\n'||c=='\r') { p++; continue; }
      break;
     }
   if(p>=len) return -1;
   return p;
  }

//--- read a string value ("..."), unescaping the basics -------------
string JsonGetString(const string json,const string key,const string def="",const int from=0)
  {
   int p=JsonFindValuePos(json,key,from);
   if(p<0) return def;
   if(StringGetCharacter(json,p)!='"') return def;
   p++;
   int len=StringLen(json);
   string out="";
   while(p<len)
     {
      ushort c=StringGetCharacter(json,p);
      if(c=='\\')
        {
         p++;
         if(p>=len) break;
         ushort e=StringGetCharacter(json,p);
         if(e=='n')      out+="\n";
         else if(e=='r') out+="\r";
         else if(e=='t') out+="\t";
         else            out+=ShortToString(e);
         p++;
         continue;
        }
      if(c=='"') break;
      out+=ShortToString(c);
      p++;
     }
   return out;
  }

//--- read a numeric value -------------------------------------------
double JsonGetNumber(const string json,const string key,const double def=0.0,const int from=0)
  {
   int p=JsonFindValuePos(json,key,from);
   if(p<0) return def;
   int len=StringLen(json);
   string num="";
   while(p<len)
     {
      ushort c=StringGetCharacter(json,p);
      if((c>='0'&&c<='9')||c=='-'||c=='+'||c=='.'||c=='e'||c=='E')
        {
         num+=ShortToString(c);
         p++;
         continue;
        }
      break;
     }
   if(StringLen(num)==0) return def;
   return StringToDouble(num);
  }

//--- read a boolean value -------------------------------------------
bool JsonGetBool(const string json,const string key,const bool def=false,const int from=0)
  {
   int p=JsonFindValuePos(json,key,from);
   if(p<0) return def;
   if(StringSubstr(json,p,4)=="true")  return true;
   if(StringSubstr(json,p,5)=="false") return false;
   return def;
  }

//--- does the document contain this key at all? ---------------------
bool JsonHasKey(const string json,const string key)
  {
   return (JsonFindValuePos(json,key,0)>=0);
  }

//+------------------------------------------------------------------+
//| Split a JSON array of flat objects into its elements.            |
//| Used for the "commands":[{...},{...}] field of a server reply.   |
//+------------------------------------------------------------------+
int JsonSplitObjectArray(const string json,const string key,string &out[])
  {
   ArrayResize(out,0);
   int p=JsonFindValuePos(json,key,0);
   if(p<0) return 0;
   if(StringGetCharacter(json,p)!='[') return 0;
   p++;

   int len=StringLen(json);
   int depth=0;
   int start=-1;
   bool inStr=false;
   bool esc=false;

   while(p<len)
     {
      ushort c=StringGetCharacter(json,p);

      if(inStr)
        {
         if(esc)            esc=false;
         else if(c=='\\')   esc=true;
         else if(c=='"')    inStr=false;
         p++;
         continue;
        }

      if(c=='"')      { inStr=true; p++; continue; }
      if(c=='{')
        {
         if(depth==0) start=p;
         depth++;
         p++;
         continue;
        }
      if(c=='}')
        {
         depth--;
         if(depth==0 && start>=0)
           {
            int k=ArraySize(out);
            ArrayResize(out,k+1);
            out[k]=StringSubstr(json,start,p-start+1);
            start=-1;
           }
         p++;
         continue;
        }
      if(c==']' && depth==0) break;
      p++;
     }
   return ArraySize(out);
  }

#endif // APEX_JSON_MQH
